## import libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### read in data

In [2]:
sat_2017 = pd.read_csv('./data/sat_2017.csv')
act_2017 = pd.read_csv('./data/act_2017.csv')

In [3]:
sat_2017

,State,Participation,Evidence-Based Reading and Writing,Math,Total
0,Alabama,5%,593,572,1165
1,Alaska,38%,547,533,1080
2,Arizona,30%,563,553,1116
3,Arkansas,3%,614,594,1208
4,California,53%,531,524,1055
5,Colorado,11%,606,595,1201
6,Connecticut,100%,530,512,1041
7,Delaware,100%,503,492,996
8,District of Columbia,100%,482,468,950
9,Florida,83%,520,497,1017
10,Georgia,61%,535,515,1050
11,Hawaii,55%,544,541,1085
12,Idaho,93%,513,493,1005
13,Illinois,9%,559,556,1115
14,Indiana,63%,542,532,1074
15,Iowa,2%,641,635,1275
16,Kansas,4%,632,628,1260
17,Kentucky,4%,631,616,1247
18,Louisiana,4%,611,586,1198
19,Maine,95%,513,499,1012
20,Maryland,69%,536,52,1060
21,Massachusetts,76%,555,551,1107
22,Michigan,100%,509,495,1005
23,Minnesota,3%,644,651,1295
24,Mississippi,2%,634,607,1242
25,Missouri,3%,640,631,1271
26,Montana,10%,605,591,1196
27,Nebraska,3%,629,625,1253
28,Nevada,26%,563,553,1116
29,New Hampshire,96%,532,520,1052
30,New Jersey,70%,530,526,1056
31,New Mexico,11%,577,561,1138
32,New York,67%,528,523,1052
33,North Carolina,49%,546,535,1081
34,North Dakota,2%,635,621,1256
35,Ohio,12%,578,570,1149
36,Oklahoma,7%,530,517,1047
37,Oregon,43%,560,548,1108
38,Pennsylvania,65%,540,531,1071
39,Rhode Island,71%,539,524,1062
40,South Carolina,50%,543,521,1064
41,South Dakota,3%,612,603,1216
42,Tennessee,5%,623,604,1228
43,Texas,62%,513,507,1020
44,Utah,3%,624,614,1238
45,Vermont,60%,562,551,1114
46,Virginia,65%,561,541,1102
47,Washington,64%,541,534,1075
48,West Virginia,14%,558,528,1086
49,Wisconsin,3%,642,649,1291
50,Wyoming,3%,626,604,1230

In [4]:
act_2017

,State,Participation,English,Math,Reading,Science,Composite
0,National,60%,20.3,20.7,21.4,21.0,21.0
1,Alabama,100%,18.9,18.4,19.7,19.4,19.2
2,Alaska,65%,18.7,19.8,20.4,19.9,19.8
3,Arizona,62%,18.6,19.8,20.1,19.8,19.7
4,Arkansas,100%,18.9,19.0,19.7,19.5,19.4
5,California,31%,22.5,22.7,23.1,22.2,22.8
6,Colorado,100%,20.1,20.3,21.2,20.9,20.8
7,Connecticut,31%,25.5,24.6,25.6,24.6,25.2
8,Delaware,18%,24.1,23.4,24.8,23.6,24.1
9,District of Columbia,32%,24.4,23.5,24.9,23.5,24.2
10,Florida,73%,19.0,19.4,21.0,19.4,19.8
11,Georgia,55%,21.0,20.9,22.0,21.3,21.4
12,Hawaii,90%,17.8,19.2,19.2,19.3,19.0
13,Idaho,38%,21.9,21.8,23.0,22.1,22.3
14,Illinois,93%,21.0,21.2,21.6,21.3,21.4
15,Indiana,35%,22.0,22.4,23.2,22.3,22.6
16,Iowa,67%,21.2,21.3,22.6,22.1,21.9
17,Kansas,73%,21.1,21.3,22.3,21.7,21.7
18,Kentucky,100%,19.6,19.4,20.5,20.1,20.0
19,Louisiana,100%,19.4,18.8,19.8,19.6,19.5
20,Maine,8%,24.2,24.0,24.8,23.7,24.3
21,Maryland,28%,23.3,23.1,24.2,2.3,23.6
22,Massachusetts,29%,25.4,25.3,25.9,24.7,25.4
23,Michigan,29%,24.1,23.7,24.5,23.8,24.1
24,Minnesota,100%,20.4,21.5,21.8,21.6,21.5
25,Mississippi,100%,18.2,18.1,18.8,18.8,18.6
26,Missouri,100%,19.8,19.9,20.8,20.5,20.4
27,Montana,100%,19.0,20.2,21.0,20.5,20.3
28,Nebraska,84%,20.9,20.9,21.9,21.5,21.4
29,Nevada,100%,16.3,18.0,18.1,18.2,17.8
30,New Hampshire,18%,25.4,25.1,26.0,24.9,25.5
31,New Jersey,34%,23.8,23.8,24.1,23.2,23.9
32,New Mexico,66%,18.6,19.4,20.4,20.0,19.7
33,New York,31%,23.8,24.0,24.6,23.9,24.2
34,North Carolina,100%,17.8,19.3,19.6,19.3,19.1
35,North Dakota,98%,19.0,20.4,20.5,20.6,20.3
36,Ohio,75%,21.2,21.6,22.5,22.0,22.0
37,Oklahoma,100%,18.5,18.8,20.1,19.6,19.4
38,Oregon,40%,21.2,21.5,22.4,21.7,21.8
39,Pennsylvania,23%,23.4,23.4,24.2,23.3,23.7
40,Rhode Island,21%,24.0,23.3,24.7,23.4,24.0
41,South Carolina,100%,17.5,18.6,19.1,18.9,18.7
42,South Dakota,80%,20.7,21.5,22.3,22.0,21.8
43,Tennessee,100%,19.5,19.2,20.1,19.9,19.8
44,Texas,45%,19.5,20.7,21.1,20.9,20.7
45,Utah,100%,19.5,19.9,20.8,20.6,20.3
46,Vermont,29%,23.3,23.1,24.4,23.2,23.6
47,Virginia,29%,23.5,23.3,24.6,23.5,23.8
48,Washington,29%,20.9,21.9,22.1,22.0,21.9
49,West Virginia,69%,20.0,19.4,21.2,20.5,20.4
50,Wisconsin,100%,19.7,20.4,20.6,20.9,20.5
51,Wyoming,100%,19.4,19.8,20.8,20.6,20.2x

## data cleaning

***I will lowercase all the column names, just for ease, and because i'm dyslexic***

In [5]:
act_2017.columns = act_2017.columns.str.lower()
sat_2017.columns  = sat_2017.columns.str.lower()

#### I have an extra row in ACT, I will drop National because I don't need it
first I will drop national in ACT's because I don't need it

In [6]:
sat_2017.shape

(51, 5)

In [7]:
act_2017.shape

(52, 7)

In [8]:
act_2017.drop(0,inplace=True)
act_2017.index -= 1

### checking for possible mistakes in the data entry

#### by comparing the data to their sorces I will be fixing the false scores. 

- [SAT](https://blog.collegevine.com/here-are-the-average-sat-scores-by-state/)
- [ACT](https://blog.prepscholar.com/act-scores-by-state-averages-highs-and-lows)

*it is worth mentioning that it is easier to find mistakes in the SAT scores, since there is a min and a max possible scores you can recive (200,800)*

In [9]:
act_2017.sort_values('science').head(1)

       state participation  english  math  reading  science composite
20  Maryland           28%     23.3  23.1     24.2      2.3      23.6

In [10]:
act_2017.loc[act_2017['state'] == 'Maryland', 'science'] = 23.2

In [11]:
sat_2017[sat_2017['math'] < 200]

       state participation  evidence-based reading and writing  math  total
20  Maryland           69%                                 536    52   1060

In [12]:
sat_2017.loc[sat_2017['state'] == 'Maryland', 'math'] = 524

**next I will inspect the data type next**

In [13]:
sat_2017.dtypes

state                                 object
participation                         object
evidence-based reading and writing     int64
math                                   int64
total                                  int64
dtype: object

In [14]:
act_2017.dtypes

state             object
participation     object
english          float64
math             float64
reading          float64
science          float64
composite         object
dtype: object

#### composite should be a numeric type data, therefore, there should be a mistake in there

In [15]:
act_2017['composite']= act_2017['composite'].apply(lambda x: float(x[:-1]) if x != float else float)

**I will also turn percent (%) into a float between (0,1)**

In [16]:
def pct_to_flt(string):
    return float(string[:-1])/100

In [17]:
sat_2017['participation'] = sat_2017['participation'].map(pct_to_flt)

act_2017['participation'] = act_2017['participation'].map(pct_to_flt)

In [18]:
act_2017.dtypes

state             object
participation    float64
english          float64
math             float64
reading          float64
science          float64
composite        float64
dtype: object

In [19]:
act_2017.dtypes

state             object
participation    float64
english          float64
math             float64
reading          float64
science          float64
composite        float64
dtype: object

#### now that I have the two dataframes cleaned and sorted I will merge the two to make one dataframe

In [20]:
scores_2017 = pd.merge(left=sat_2017,
                       right=act_2017,
                       how='inner',
                       on='state')

In [21]:
scores_2017.head()

,state,participation_x,evidence-based reading and writing,math_x,total,participation_y,english,math_y,reading,science,composite
0,Alabama,0.05,593,572,1165,1.00,18.9,18.4,19.7,19.4,19.0
1,Alaska,0.38,547,533,1080,0.65,18.7,19.8,20.4,19.9,19.0
2,Arizona,0.30,563,553,1116,0.62,18.6,19.8,20.1,19.8,19.0
3,Arkansas,0.03,614,594,1208,1.00,18.9,19.0,19.7,19.5,19.0
4,California,0.53,531,524,1055,0.31,22.5,22.7,23.1,22.2,22.0

**I will rename the columns**

In [22]:
scores_2017.rename(columns = {
                    "participation_x": 'sat_partic_17', 
"evidence-based reading and writing":"sat_read_write_17", 
                            "math_x": "sat_math_17",
                             "total":"sat_total_17",
                    "participation_y":"act_partic_17",
                             "english":"act_eng_17",
                             "math_y":"act_math_17",
                             "reading":"act_read_17",
                             "science":"act_sci_17",
                             "composite":"act_composite_17"}, inplace=True)

Lastly I will save the dataframe incase I need it later

In [23]:
scores_2017.to_csv('./data/combined_2017.csv',index=False)

### I will read in the 2018 data frames next

In [24]:
sat_2018 = pd.read_csv('./data/sat_2018.csv')
act_2018 = pd.read_csv('./data/act_2018.csv')

In [25]:
sat_2018

,State,Participation,Evidence-Based Reading and Writing,Math,Total
0,Alabama,6%,595,571,1166
1,Alaska,43%,562,544,1106
2,Arizona,29%,577,572,1149
3,Arkansas,5%,592,576,1169
4,California,60%,540,536,1076
5,Colorado,100%,519,506,1025
6,Connecticut,100%,535,519,1053
7,Delaware,100%,505,492,998
8,District of Columbia,92%,497,480,977
9,Florida,56%,550,549,1099
10,Georgia,70%,542,522,1064
11,Hawaii,56%,480,530,1010
12,Idaho,100%,508,493,1001
13,Illinois,99%,513,506,1019
14,Indiana,63%,542,532,1074
15,Iowa,3%,634,631,1265
16,Kansas,4%,633,631,1265
17,Kentucky,4%,630,618,1248
18,Louisiana,4%,615,595,1210
19,Maine,99%,512,501,1013
20,Maryland,76%,545,535,1080
21,Massachusetts,80%,562,563,1125
22,Michigan,100%,511,499,1011
23,Minnesota,4%,643,655,1298
24,Mississippi,3%,630,606,1236
25,Missouri,4%,633,629,1262
26,Montana,10%,606,592,1198
27,Nebraska,3%,629,623,1252
28,Nevada,23%,574,566,1140
29,New Hampshire,96%,535,528,1063
30,New Jersey,82%,547,547,1094
31,New Mexico,16%,552,540,1093
32,New York,79%,534,534,1068
33,North Carolina,52%,554,543,1098
34,North Dakota,2%,640,643,1283
35,Oklahoma,8%,541,521,1062
36,Ohio,18%,552,547,1099
37,Oregon,48%,564,553,1117
38,Pennsylvania,70%,547,539,1086
39,Rhode Island,97%,513,505,1018
40,South Carolina,55%,547,523,1070
41,South Dakota,3%,622,618,1240
42,Tennessee,6%,624,607,1231
43,Texas,66%,520,512,1032
44,Utah,4%,480,530,1010
45,Vermont,64%,565,554,1120
46,Virginia,68%,567,550,1117
47,Washington,69%,543,538,1081
48,West Virginia,28%,513,486,999
49,Wisconsin,3%,641,653,1294
50,Wyoming,3%,633,625,1257

In [26]:
act_2018

                   State Participation  Composite
0                Alabama          100%       19.1
1                 Alaska           33%       20.8
2                Arizona           66%       19.2
3               Arkansas          100%       19.4
4             California           27%       22.7
5               Colorado           30%       23.9
6            Connecticut           26%       25.6
7               Delaware           17%       23.8
8   District of columbia           32%       23.6
9                Florida           66%       19.9
10               Georgia           53%       21.4
11                Hawaii           89%       18.9
12                 Idaho           36%       22.3
13              Illinois           43%       23.9
14               Indiana           32%       22.5
15                  Iowa           68%       21.8
16                Kansas           71%       21.6
17              Kentucky          100%       20.2
18             Louisiana          100%       19.2
19                 Maine            7%       24.0
20                 Maine            7%       24.0
21              Maryland           31%       22.5
22         Massachusetts           25%       25.5
23              Michigan           22%       24.2
24             Minnesota           99%       21.3
25           Mississippi          100%       18.6
26              Missouri          100%       20.0
27               Montana          100%       20.0
28              Nebraska          100%       20.1
29                Nevada          100%       17.7
30         New Hampshire           16%       25.1
31            New Jersey           31%       23.7
32            New Mexico           67%       19.4
33              New York           27%       24.5
34        North Carolina          100%       19.1
35          North Dakota           98%       20.3
36                  Ohio          100%       20.3
37              Oklahoma          100%       19.3
38                Oregon           42%       21.3
39          Pennsylvania           20%       23.5
40          Rhode Island           15%       24.2
41        South Carolina          100%       18.3
42          South Dakota           77%       21.9
43             Tennessee          100%       19.6
44                 Texas           45%       20.7
45                  Utah          100%       20.4
46               Vermont           24%       24.1
47              Virginia           24%       23.9
48            Washington           24%       22.2
49         West Virginia           65%       20.3
50             Wisconsin          100%       20.5
51               Wyoming          100%       20.0

In [27]:
act_2018.columns = act_2018.columns.str.lower()
sat_2018.columns  = sat_2018.columns.str.lower()

In [28]:
sat_2018.shape

(51, 5)

In [29]:
act_2018.shape

(52, 3)

**right away I have an extra set row in the act, so I will inspect what it is**

In [30]:
act_2018['state'].value_counts().head(1)

Maine    2
Name: state, dtype: int64

In [31]:
act_2018.loc[act_2018['state'] == 'Maine']

    state participation  composite
19  Maine            7%       24.0
20  Maine            7%       24.0

**I have a repeated Main, so I need to drop it**

In [32]:
act_2018.drop(20, inplace=True)
act_2018.index = range(0, 51)

In [33]:
act_2018.shape

(51, 3)

In [34]:
sat_2018['participation'] = sat_2018['participation'].map(pct_to_flt)
act_2018['participation'] = act_2018['participation'].map(pct_to_flt)

In [35]:
scores_2018 = pd.merge(left=sat_2018,
                       right=act_2018,
                       how='inner',on='state')

In [36]:
scores_2018

,state,participation_x,evidence-based reading and writing,math,total,participation_y,composite
0,Alabama,0.06,595,571,1166,1.00,19.1
1,Alaska,0.43,562,544,1106,0.33,20.8
2,Arizona,0.29,577,572,1149,0.66,19.2
3,Arkansas,0.05,592,576,1169,1.00,19.4
4,California,0.60,540,536,1076,0.27,22.7
5,Colorado,1.00,519,506,1025,0.30,23.9
6,Connecticut,1.00,535,519,1053,0.26,25.6
7,Delaware,1.00,505,492,998,0.17,23.8
8,Florida,0.56,550,549,1099,0.66,19.9
9,Georgia,0.70,542,522,1064,0.53,21.4
10,Hawaii,0.56,480,530,1010,0.89,18.9
11,Idaho,1.00,508,493,1001,0.36,22.3
12,Illinois,0.99,513,506,1019,0.43,23.9
13,Indiana,0.63,542,532,1074,0.32,22.5
14,Iowa,0.03,634,631,1265,0.68,21.8
15,Kansas,0.04,633,631,1265,0.71,21.6
16,Kentucky,0.04,630,618,1248,1.00,20.2
17,Louisiana,0.04,615,595,1210,1.00,19.2
18,Maine,0.99,512,501,1013,0.07,24.0
19,Maryland,0.76,545,535,1080,0.31,22.5
20,Massachusetts,0.80,562,563,1125,0.25,25.5
21,Michigan,1.00,511,499,1011,0.22,24.2
22,Minnesota,0.04,643,655,1298,0.99,21.3
23,Mississippi,0.03,630,606,1236,1.00,18.6
24,Missouri,0.04,633,629,1262,1.00,20.0
25,Montana,0.10,606,592,1198,1.00,20.0
26,Nebraska,0.03,629,623,1252,1.00,20.1
27,Nevada,0.23,574,566,1140,1.00,17.7
28,New Hampshire,0.96,535,528,1063,0.16,25.1
29,New Jersey,0.82,547,547,1094,0.31,23.7
30,New Mexico,0.16,552,540,1093,0.67,19.4
31,New York,0.79,534,534,1068,0.27,24.5
32,North Carolina,0.52,554,543,1098,1.00,19.1
33,North Dakota,0.02,640,643,1283,0.98,20.3
34,Oklahoma,0.08,541,521,1062,1.00,19.3
35,Ohio,0.18,552,547,1099,1.00,20.3
36,Oregon,0.48,564,553,1117,0.42,21.3
37,Pennsylvania,0.70,547,539,1086,0.20,23.5
38,Rhode Island,0.97,513,505,1018,0.15,24.2
39,South Carolina,0.55,547,523,1070,1.00,18.3
40,South Dakota,0.03,622,618,1240,0.77,21.9
41,Tennessee,0.06,624,607,1231,1.00,19.6
42,Texas,0.66,520,512,1032,0.45,20.7
43,Utah,0.04,480,530,1010,1.00,20.4
44,Vermont,0.64,565,554,1120,0.24,24.1
45,Virginia,0.68,567,550,1117,0.24,23.9
46,Washington,0.69,543,538,1081,0.24,22.2
47,West Virginia,0.28,513,486,999,0.65,20.3
48,Wisconsin,0.03,641,653,1294,1.00,20.5
49,Wyoming,0.03,633,625,1257,1.00,20.0

I have a row misssing, therefore one of the states must have had a diffrent name or spelling on one of the dataframes

In [37]:
sat_2018.state.isin(act_2018.state).astype(int)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    1
48    1
49    1
50    1
Name: state, dtype: int64

In [38]:
print(f'sat index 8: {sat_2018.iloc[8,0]}')
print(f'act index 8: {act_2018.iloc[8,0]}')

sat index 8: District of Columbia
act index 8: District of columbia

In [39]:
act_2018.loc[act_2018['state'] == 'District of columbia','state'] = 'District of Columbia'

In [40]:
scores_2018 = pd.merge(left=sat_2018,
                       right=act_2018,
                       how='inner',on='state')

In [41]:
scores_2018.shape

(51, 7)

In [42]:
scores_2018.rename(columns={
    'participation_y': 'act_partic_18',
    'participation_x': 'sat_partic_18',
    "evidence-based reading and writing":"sat_read_write_18",
    'math':'sat_math_18',
    'total':'sat_total_18',
    'composite':"act_composite_18"}, inplace=True)

In [43]:
scores_2018.head()

,state,sat_partic_18,sat_read_write_18,sat_math_18,sat_total_18,act_partic_18,act_composite_18
0,Alabama,0.06,595,571,1166,1.00,19.1
1,Alaska,0.43,562,544,1106,0.33,20.8
2,Arizona,0.29,577,572,1149,0.66,19.2
3,Arkansas,0.05,592,576,1169,1.00,19.4
4,California,0.60,540,536,1076,0.27,22.7

In [44]:
scores_2018.to_csv('./data/combined_2018.csv', index=False)

### lastly I will meger 2017 and 2018 data together

In [45]:
scores = pd.merge(left=scores_2017,
                  right=scores_2018,
                  how='inner',
                  on='state')

In [46]:
scores.head()

,state,sat_partic_17,sat_read_write_17,sat_math_17,sat_total_17,act_partic_17,act_eng_17,act_math_17,act_read_17,act_sci_17,act_composite_17,sat_partic_18,sat_read_write_18,sat_math_18,sat_total_18,act_partic_18,act_composite_18
0,Alabama,0.05,593,572,1165,1.00,18.9,18.4,19.7,19.4,19.0,0.06,595,571,1166,1.00,19.1
1,Alaska,0.38,547,533,1080,0.65,18.7,19.8,20.4,19.9,19.0,0.43,562,544,1106,0.33,20.8
2,Arizona,0.30,563,553,1116,0.62,18.6,19.8,20.1,19.8,19.0,0.29,577,572,1149,0.66,19.2
3,Arkansas,0.03,614,594,1208,1.00,18.9,19.0,19.7,19.5,19.0,0.05,592,576,1169,1.00,19.4
4,California,0.53,531,524,1055,0.31,22.5,22.7,23.1,22.2,22.0,0.60,540,536,1076,0.27,22.7

In [47]:
scores.to_csv('./data/combined.csv', index=False)

### now I will read in the poverty data.
#### this data is *Percentage of People in Poverty by State Using 2-Year Average, 2017-2018.*

In [48]:
poverty = pd.read_csv('./data/state.csv', encoding='iso-8859-1', header=None)

In [49]:
poverty

                        0     1
0                 Alabama  15.6
1                  Alaska  12.6
2                 Arizona  13.2
3                Arkansas  15.4
4              California  12.0
5                Colorado   9.0
6             Connecticut  10.4
7                Delaware   8.1
8   District of Columbia
  14.3
9                 Florida  13.5
10                    NaN   NaN
11                Georgia  14.0
12                 Hawaii   9.9
13                  Idaho  11.5
14               Illinois  10.9
15                Indiana  11.6
16                   Iowa   8.2
17                 Kansas  10.9
18               Kentucky  14.6
19              Louisiana  19.8
20                  Maine  12.0
21                    NaN   NaN
22               Maryland   7.8
23          Massachusetts  10.0
24               Michigan  11.0
25              Minnesota   8.2
26            Mississippi  19.0
27               Missouri  11.9
28                Montana  10.3
29               Nebraska  11.0
30                 Nevada  13.1
31          New Hampshire   6.6
32                    NaN   NaN
33             New Jersey   9.1
34             New Mexico  18.2
35               New York  11.9
36         North Carolina  14.1
37           North Dakota  11.1
38                   Ohio  12.4
39               Oklahoma  13.1
40                 Oregon  10.6
41           Pennsylvania  11.4
42           Rhode Island  10.1
43                    NaN   NaN
44         South Carolina  14.0
45           South Dakota  10.7
46              Tennessee  11.7
47                  Texas  13.4
48                   Utah   7.8
49                Vermont   9.2
50               Virginia  10.1
51             Washington   9.7
52          West Virginia  16.5
53              Wisconsin   8.9
54                Wyoming  11.2

***right away I can tell that there are some Nane rows, so i need to drop them, and replace the index***

In [50]:
poverty.dropna(inplace=True)
poverty.reset_index(inplace=True)
poverty.drop(columns='index')

                        0     1
0                 Alabama  15.6
1                  Alaska  12.6
2                 Arizona  13.2
3                Arkansas  15.4
4              California  12.0
5                Colorado   9.0
6             Connecticut  10.4
7                Delaware   8.1
8   District of Columbia
  14.3
9                 Florida  13.5
10                Georgia  14.0
11                 Hawaii   9.9
12                  Idaho  11.5
13               Illinois  10.9
14                Indiana  11.6
15                   Iowa   8.2
16                 Kansas  10.9
17               Kentucky  14.6
18              Louisiana  19.8
19                  Maine  12.0
20               Maryland   7.8
21          Massachusetts  10.0
22               Michigan  11.0
23              Minnesota   8.2
24            Mississippi  19.0
25               Missouri  11.9
26                Montana  10.3
27               Nebraska  11.0
28                 Nevada  13.1
29          New Hampshire   6.6
30             New Jersey   9.1
31             New Mexico  18.2
32               New York  11.9
33         North Carolina  14.1
34           North Dakota  11.1
35                   Ohio  12.4
36               Oklahoma  13.1
37                 Oregon  10.6
38           Pennsylvania  11.4
39           Rhode Island  10.1
40         South Carolina  14.0
41           South Dakota  10.7
42              Tennessee  11.7
43                  Texas  13.4
44                   Utah   7.8
45                Vermont   9.2
46               Virginia  10.1
47             Washington   9.7
48          West Virginia  16.5
49              Wisconsin   8.9
50                Wyoming  11.2

**and rename the columns**

In [51]:
poverty.columns = ['index','state', 'poverty_rate']
poverty.drop(columns='index', inplace= True)

In [52]:
poverty.shape

(51, 2)

In [53]:
poverty

                    state  poverty_rate
0                 Alabama          15.6
1                  Alaska          12.6
2                 Arizona          13.2
3                Arkansas          15.4
4              California          12.0
5                Colorado           9.0
6             Connecticut          10.4
7                Delaware           8.1
8   District of Columbia
          14.3
9                 Florida          13.5
10                Georgia          14.0
11                 Hawaii           9.9
12                  Idaho          11.5
13               Illinois          10.9
14                Indiana          11.6
15                   Iowa           8.2
16                 Kansas          10.9
17               Kentucky          14.6
18              Louisiana          19.8
19                  Maine          12.0
20               Maryland           7.8
21          Massachusetts          10.0
22               Michigan          11.0
23              Minnesota           8.2
24            Mississippi          19.0
25               Missouri          11.9
26                Montana          10.3
27               Nebraska          11.0
28                 Nevada          13.1
29          New Hampshire           6.6
30             New Jersey           9.1
31             New Mexico          18.2
32               New York          11.9
33         North Carolina          14.1
34           North Dakota          11.1
35                   Ohio          12.4
36               Oklahoma          13.1
37                 Oregon          10.6
38           Pennsylvania          11.4
39           Rhode Island          10.1
40         South Carolina          14.0
41           South Dakota          10.7
42              Tennessee          11.7
43                  Texas          13.4
44                   Utah           7.8
45                Vermont           9.2
46               Virginia          10.1
47             Washington           9.7
48          West Virginia          16.5
49              Wisconsin           8.9
50                Wyoming          11.2

In [54]:
poverty.shape

(51, 2)

### last thing to do is to put the poverty data and the standardized testing data together

In [55]:
data = pd.merge(left=scores,
                  right=poverty,
                  on='state',
                  how='outer')

In [56]:
data

,state,sat_partic_17,sat_read_write_17,sat_math_17,sat_total_17,act_partic_17,act_eng_17,act_math_17,act_read_17,act_sci_17,act_composite_17,sat_partic_18,sat_read_write_18,sat_math_18,sat_total_18,act_partic_18,act_composite_18,poverty_rate
0,Alabama,0.05,593.0,572.0,1165.0,1.00,18.9,18.4,19.7,19.4,19.0,0.06,595.0,571.0,1166.0,1.00,19.1,15.6
1,Alaska,0.38,547.0,533.0,1080.0,0.65,18.7,19.8,20.4,19.9,19.0,0.43,562.0,544.0,1106.0,0.33,20.8,12.6
2,Arizona,0.30,563.0,553.0,1116.0,0.62,18.6,19.8,20.1,19.8,19.0,0.29,577.0,572.0,1149.0,0.66,19.2,13.2
3,Arkansas,0.03,614.0,594.0,1208.0,1.00,18.9,19.0,19.7,19.5,19.0,0.05,592.0,576.0,1169.0,1.00,19.4,15.4
4,California,0.53,531.0,524.0,1055.0,0.31,22.5,22.7,23.1,22.2,22.0,0.60,540.0,536.0,1076.0,0.27,22.7,12.0
5,Colorado,0.11,606.0,595.0,1201.0,1.00,20.1,20.3,21.2,20.9,20.0,1.00,519.0,506.0,1025.0,0.30,23.9,9.0
6,Connecticut,1.00,530.0,512.0,1041.0,0.31,25.5,24.6,25.6,24.6,25.0,1.00,535.0,519.0,1053.0,0.26,25.6,10.4
7,Delaware,1.00,503.0,492.0,996.0,0.18,24.1,23.4,24.8,23.6,24.0,1.00,505.0,492.0,998.0,0.17,23.8,8.1
8,District of Columbia,1.00,482.0,468.0,950.0,0.32,24.4,23.5,24.9,23.5,24.0,0.92,497.0,480.0,977.0,0.32,23.6,NaN
9,Florida,0.83,520.0,497.0,1017.0,0.73,19.0,19.4,21.0,19.4,19.0,0.56,550.0,549.0,1099.0,0.66,19.9,13.5
10,Georgia,0.61,535.0,515.0,1050.0,0.55,21.0,20.9,22.0,21.3,21.0,0.70,542.0,522.0,1064.0,0.53,21.4,14.0
11,Hawaii,0.55,544.0,541.0,1085.0,0.90,17.8,19.2,19.2,19.3,19.0,0.56,480.0,530.0,1010.0,0.89,18.9,9.9
12,Idaho,0.93,513.0,493.0,1005.0,0.38,21.9,21.8,23.0,22.1,22.0,1.00,508.0,493.0,1001.0,0.36,22.3,11.5
13,Illinois,0.09,559.0,556.0,1115.0,0.93,21.0,21.2,21.6,21.3,21.0,0.99,513.0,506.0,1019.0,0.43,23.9,10.9
14,Indiana,0.63,542.0,532.0,1074.0,0.35,22.0,22.4,23.2,22.3,22.0,0.63,542.0,532.0,1074.0,0.32,22.5,11.6
15,Iowa,0.02,641.0,635.0,1275.0,0.67,21.2,21.3,22.6,22.1,21.0,0.03,634.0,631.0,1265.0,0.68,21.8,8.2
16,Kansas,0.04,632.0,628.0,1260.0,0.73,21.1,21.3,22.3,21.7,21.0,0.04,633.0,631.0,1265.0,0.71,21.6,10.9
17,Kentucky,0.04,631.0,616.0,1247.0,1.00,19.6,19.4,20.5,20.1,20.0,0.04,630.0,618.0,1248.0,1.00,20.2,14.6
18,Louisiana,0.04,611.0,586.0,1198.0,1.00,19.4,18.8,19.8,19.6,19.0,0.04,615.0,595.0,1210.0,1.00,19.2,19.8
19,Maine,0.95,513.0,499.0,1012.0,0.08,24.2,24.0,24.8,23.7,24.0,0.99,512.0,501.0,1013.0,0.07,24.0,12.0
20,Maryland,0.69,536.0,524.0,1060.0,0.28,23.3,23.1,24.2,23.2,23.0,0.76,545.0,535.0,1080.0,0.31,22.5,7.8
21,Massachusetts,0.76,555.0,551.0,1107.0,0.29,25.4,25.3,25.9,24.7,25.0,0.80,562.0,563.0,1125.0,0.25,25.5,10.0
22,Michigan,1.00,509.0,495.0,1005.0,0.29,24.1,23.7,24.5,23.8,24.0,1.00,511.0,499.0,1011.0,0.22,24.2,11.0
23,Minnesota,0.03,644.0,651.0,1295.0,1.00,20.4,21.5,21.8,21.6,21.0,0.04,643.0,655.0,1298.0,0.99,21.3,8.2
24,Mississippi,0.02,634.0,607.0,1242.0,1.00,18.2,18.1,18.8,18.8,18.0,0.03,630.0,606.0,1236.0,1.00,18.6,19.0
25,Missouri,0.03,640.0,631.0,1271.0,1.00,19.8,19.9,20.8,20.5,20.0,0.04,633.0,629.0,1262.0,1.00,20.0,11.9
26,Montana,0.10,605.0,591.0,1196.0,1.00,19.0,20.2,21.0,20.5,20.0,0.10,606.0,592.0,1198.0,1.00,20.0,10.3
27,Nebraska,0.03,629.0,625.0,1253.0,0.84,20.9,20.9,21.9,21.5,21.0,0.03,629.0,623.0,1252.0,1.00,20.1,11.0
28,Nevada,0.26,563.0,553.0,1116.0,1.00,16.3,18.0,18.1,18.2,17.0,0.23,574.0,566.0,1140.0,1.00,17.7,13.1
29,New Hampshire,0.96,532.0,520.0,1052.0,0.18,25.4,25.1,26.0,24.9,25.0,0.96,535.0,528.0,1063.0,0.16,25.1,6.6
30,New Jersey,0.70,530.0,526.0,1056.0,0.34,23.8,23.8,24.1,23.2,23.0,0.82,547.0,547.0,1094.0,0.31,23.7,9.1
31,New Mexico,0.11,577.0,561.0,1138.0,0.66,18.6,19.4,20.4,20.0,19.0,0.16,552.0,540.0,1093.0,0.67,19.4,18.2
32,New York,0.67,528.0,523.0,1052.0,0.31,23.8,24.0,24.6,23.9,24.0,0.79,534.0,534.0,1068.0,0.27,24.5,11.9
33,North Carolina,0.49,546.0,535.0,1081.0,1.00,17.8,19.3,19.6,19.3,19.0,0.52,554.0,543.0,1098.0,1.00,19.1,14.1
34,North Dakota,0.02,635.0,621.0,1256.0,0.98,19.0,20.4,20.5,20.6,20.0,0.02,640.0,643.0,1283.0,0.98,20.3,11.1
35,Ohio,0.12,578.0,570.0,1149.0,0.75,21.2,21.6,22.5,22.0,22.0,0.18,552.0,547.0,1099.0,1.00,20.3,12.4
36,Oklahoma,0.07,530.0,517.0,1047.0,1.00,18.5,18.8,20.1,19.6,19.0,0.08,541.0,521.0,1062.0,1.00,19.3,13.1
37,Oregon,0.43,560.0,548.0,1108.0,0.40,21.2,21.5,22.4,21.7,21.0,0.48,564.0,553.0,1117.0,0.42,21.3,10.6
38,Pennsylvania,0.65,540.0,531.0,1071.0,0.23,23.4,23.4,24.2,23.3,23.0,0.70,547.0,539.0,1086.0,0.20,23.5,11.4
39,Rhode Island,0.71,539.0,524.0,1062.0,0.21,24.0,23.3,24.7,23.4,24.0,0.97,513.0,505.0,1018.0,0.15,24.2,10.1
40,South Carolina,0.50,543.0,521.0,1064.0,1.00,17.5,18.6,19.1,18.9,18.0,0.55,547.0,523.0,1070.0,1.00,18.3,14.0
41,South Dakota,0.03,612.0,603.0,1216.0,0.80,20.7,21.5,22.3,22.0,21.0,0.03,622.0,618.0,1240.0,0.77,21.9,10.7
42,Tennessee,0.05,623.0,604.0,1228.0,1.00,19.5,19.2,20.1,19.9,19.0,0.06,624.0,607.0,1231.0,1.00,19.6,11.7
43,Texas,0.62,513.0,507.0,1020.0,0.45,19.5,20.7,21.1,20.9,20.0,0.66,520.0,512.0,1032.0,0.45,20.7,13.4
44,Utah,0.03,624.0,614.0,1238.0,1.00,19.5,19.9,20.8,20.6,20.0,0.04,480.0,530.0,1010.0,1.00,20.4,7.8
45,Vermont,0.60,562.0,551.0,1114.0,0.29,23.3,23.1,24.4,23.2,23.0,0.64,565.0,554.0,1120.0,0.24,24.1,9.2
46,Virginia,0.65,561.0,541.0,1102.0,0.29,23.5,23.3,24.6,23.5,23.0,0.68,567.0,550.0,1117.0,0.24,23.9,10.1
47,Washington,0.64,541.0,534.0,1075.0,0.29,20.9,21.9,22.1,22.0,21.0,0.69,543.0,538.0,1081.0,0.24,22.2,9.7
48,West Virginia,0.14,558.0,528.0,1086.0,0.69,20.0,19.4,21.2,20.5,20.0,0.28,513.0,486.0,999.0,0.65,20.3,16.5
49,Wisconsin,0.03,642.0,649.0,1291.0,1.00,19.7,20.4,20.6,20.9,20.0,0.03,641.0,653.0,1294.0,1.00,20.5,8.9
50,Wyoming,0.03,626.0,604.0,1230.0,1.00,19.4,19.8,20.8,20.6,20.2,0.03,633.0,625.0,1257.0,1.00,20.0,11.2
51,District of Columbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.3

#### seems like there is onceagain a problem with the DC data

In [57]:
scores['state'].isin(poverty.state).astype(int)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    1
48    1
49    1
50    1
Name: state, dtype: int64

In [58]:
print(f'poverty index 8: {poverty.iloc[8,0]}')
print(f'scores index 8: {scores.iloc[8,0]}')

poverty index 8: District of Columbia
scores index 8: District of Columbia

Well, I don't know what to say they look identical, and I just double chedked with command f and my computer seems to think they are identical. so i'm just going to replace the NaN at [8,17] with the coreect data and drop the last row

In [59]:
data.iloc[8, 17] = 14.3
data.dropna(inplace=True)

In [60]:
data

,state,sat_partic_17,sat_read_write_17,sat_math_17,sat_total_17,act_partic_17,act_eng_17,act_math_17,act_read_17,act_sci_17,act_composite_17,sat_partic_18,sat_read_write_18,sat_math_18,sat_total_18,act_partic_18,act_composite_18,poverty_rate
0,Alabama,0.05,593.0,572.0,1165.0,1.00,18.9,18.4,19.7,19.4,19.0,0.06,595.0,571.0,1166.0,1.00,19.1,15.6
1,Alaska,0.38,547.0,533.0,1080.0,0.65,18.7,19.8,20.4,19.9,19.0,0.43,562.0,544.0,1106.0,0.33,20.8,12.6
2,Arizona,0.30,563.0,553.0,1116.0,0.62,18.6,19.8,20.1,19.8,19.0,0.29,577.0,572.0,1149.0,0.66,19.2,13.2
3,Arkansas,0.03,614.0,594.0,1208.0,1.00,18.9,19.0,19.7,19.5,19.0,0.05,592.0,576.0,1169.0,1.00,19.4,15.4
4,California,0.53,531.0,524.0,1055.0,0.31,22.5,22.7,23.1,22.2,22.0,0.60,540.0,536.0,1076.0,0.27,22.7,12.0
5,Colorado,0.11,606.0,595.0,1201.0,1.00,20.1,20.3,21.2,20.9,20.0,1.00,519.0,506.0,1025.0,0.30,23.9,9.0
6,Connecticut,1.00,530.0,512.0,1041.0,0.31,25.5,24.6,25.6,24.6,25.0,1.00,535.0,519.0,1053.0,0.26,25.6,10.4
7,Delaware,1.00,503.0,492.0,996.0,0.18,24.1,23.4,24.8,23.6,24.0,1.00,505.0,492.0,998.0,0.17,23.8,8.1
8,District of Columbia,1.00,482.0,468.0,950.0,0.32,24.4,23.5,24.9,23.5,24.0,0.92,497.0,480.0,977.0,0.32,23.6,14.3
9,Florida,0.83,520.0,497.0,1017.0,0.73,19.0,19.4,21.0,19.4,19.0,0.56,550.0,549.0,1099.0,0.66,19.9,13.5
10,Georgia,0.61,535.0,515.0,1050.0,0.55,21.0,20.9,22.0,21.3,21.0,0.70,542.0,522.0,1064.0,0.53,21.4,14.0
11,Hawaii,0.55,544.0,541.0,1085.0,0.90,17.8,19.2,19.2,19.3,19.0,0.56,480.0,530.0,1010.0,0.89,18.9,9.9
12,Idaho,0.93,513.0,493.0,1005.0,0.38,21.9,21.8,23.0,22.1,22.0,1.00,508.0,493.0,1001.0,0.36,22.3,11.5
13,Illinois,0.09,559.0,556.0,1115.0,0.93,21.0,21.2,21.6,21.3,21.0,0.99,513.0,506.0,1019.0,0.43,23.9,10.9
14,Indiana,0.63,542.0,532.0,1074.0,0.35,22.0,22.4,23.2,22.3,22.0,0.63,542.0,532.0,1074.0,0.32,22.5,11.6
15,Iowa,0.02,641.0,635.0,1275.0,0.67,21.2,21.3,22.6,22.1,21.0,0.03,634.0,631.0,1265.0,0.68,21.8,8.2
16,Kansas,0.04,632.0,628.0,1260.0,0.73,21.1,21.3,22.3,21.7,21.0,0.04,633.0,631.0,1265.0,0.71,21.6,10.9
17,Kentucky,0.04,631.0,616.0,1247.0,1.00,19.6,19.4,20.5,20.1,20.0,0.04,630.0,618.0,1248.0,1.00,20.2,14.6
18,Louisiana,0.04,611.0,586.0,1198.0,1.00,19.4,18.8,19.8,19.6,19.0,0.04,615.0,595.0,1210.0,1.00,19.2,19.8
19,Maine,0.95,513.0,499.0,1012.0,0.08,24.2,24.0,24.8,23.7,24.0,0.99,512.0,501.0,1013.0,0.07,24.0,12.0
20,Maryland,0.69,536.0,524.0,1060.0,0.28,23.3,23.1,24.2,23.2,23.0,0.76,545.0,535.0,1080.0,0.31,22.5,7.8
21,Massachusetts,0.76,555.0,551.0,1107.0,0.29,25.4,25.3,25.9,24.7,25.0,0.80,562.0,563.0,1125.0,0.25,25.5,10.0
22,Michigan,1.00,509.0,495.0,1005.0,0.29,24.1,23.7,24.5,23.8,24.0,1.00,511.0,499.0,1011.0,0.22,24.2,11.0
23,Minnesota,0.03,644.0,651.0,1295.0,1.00,20.4,21.5,21.8,21.6,21.0,0.04,643.0,655.0,1298.0,0.99,21.3,8.2
24,Mississippi,0.02,634.0,607.0,1242.0,1.00,18.2,18.1,18.8,18.8,18.0,0.03,630.0,606.0,1236.0,1.00,18.6,19.0
25,Missouri,0.03,640.0,631.0,1271.0,1.00,19.8,19.9,20.8,20.5,20.0,0.04,633.0,629.0,1262.0,1.00,20.0,11.9
26,Montana,0.10,605.0,591.0,1196.0,1.00,19.0,20.2,21.0,20.5,20.0,0.10,606.0,592.0,1198.0,1.00,20.0,10.3
27,Nebraska,0.03,629.0,625.0,1253.0,0.84,20.9,20.9,21.9,21.5,21.0,0.03,629.0,623.0,1252.0,1.00,20.1,11.0
28,Nevada,0.26,563.0,553.0,1116.0,1.00,16.3,18.0,18.1,18.2,17.0,0.23,574.0,566.0,1140.0,1.00,17.7,13.1
29,New Hampshire,0.96,532.0,520.0,1052.0,0.18,25.4,25.1,26.0,24.9,25.0,0.96,535.0,528.0,1063.0,0.16,25.1,6.6
30,New Jersey,0.70,530.0,526.0,1056.0,0.34,23.8,23.8,24.1,23.2,23.0,0.82,547.0,547.0,1094.0,0.31,23.7,9.1
31,New Mexico,0.11,577.0,561.0,1138.0,0.66,18.6,19.4,20.4,20.0,19.0,0.16,552.0,540.0,1093.0,0.67,19.4,18.2
32,New York,0.67,528.0,523.0,1052.0,0.31,23.8,24.0,24.6,23.9,24.0,0.79,534.0,534.0,1068.0,0.27,24.5,11.9
33,North Carolina,0.49,546.0,535.0,1081.0,1.00,17.8,19.3,19.6,19.3,19.0,0.52,554.0,543.0,1098.0,1.00,19.1,14.1
34,North Dakota,0.02,635.0,621.0,1256.0,0.98,19.0,20.4,20.5,20.6,20.0,0.02,640.0,643.0,1283.0,0.98,20.3,11.1
35,Ohio,0.12,578.0,570.0,1149.0,0.75,21.2,21.6,22.5,22.0,22.0,0.18,552.0,547.0,1099.0,1.00,20.3,12.4
36,Oklahoma,0.07,530.0,517.0,1047.0,1.00,18.5,18.8,20.1,19.6,19.0,0.08,541.0,521.0,1062.0,1.00,19.3,13.1
37,Oregon,0.43,560.0,548.0,1108.0,0.40,21.2,21.5,22.4,21.7,21.0,0.48,564.0,553.0,1117.0,0.42,21.3,10.6
38,Pennsylvania,0.65,540.0,531.0,1071.0,0.23,23.4,23.4,24.2,23.3,23.0,0.70,547.0,539.0,1086.0,0.20,23.5,11.4
39,Rhode Island,0.71,539.0,524.0,1062.0,0.21,24.0,23.3,24.7,23.4,24.0,0.97,513.0,505.0,1018.0,0.15,24.2,10.1
40,South Carolina,0.50,543.0,521.0,1064.0,1.00,17.5,18.6,19.1,18.9,18.0,0.55,547.0,523.0,1070.0,1.00,18.3,14.0
41,South Dakota,0.03,612.0,603.0,1216.0,0.80,20.7,21.5,22.3,22.0,21.0,0.03,622.0,618.0,1240.0,0.77,21.9,10.7
42,Tennessee,0.05,623.0,604.0,1228.0,1.00,19.5,19.2,20.1,19.9,19.0,0.06,624.0,607.0,1231.0,1.00,19.6,11.7
43,Texas,0.62,513.0,507.0,1020.0,0.45,19.5,20.7,21.1,20.9,20.0,0.66,520.0,512.0,1032.0,0.45,20.7,13.4
44,Utah,0.03,624.0,614.0,1238.0,1.00,19.5,19.9,20.8,20.6,20.0,0.04,480.0,530.0,1010.0,1.00,20.4,7.8
45,Vermont,0.60,562.0,551.0,1114.0,0.29,23.3,23.1,24.4,23.2,23.0,0.64,565.0,554.0,1120.0,0.24,24.1,9.2
46,Virginia,0.65,561.0,541.0,1102.0,0.29,23.5,23.3,24.6,23.5,23.0,0.68,567.0,550.0,1117.0,0.24,23.9,10.1
47,Washington,0.64,541.0,534.0,1075.0,0.29,20.9,21.9,22.1,22.0,21.0,0.69,543.0,538.0,1081.0,0.24,22.2,9.7
48,West Virginia,0.14,558.0,528.0,1086.0,0.69,20.0,19.4,21.2,20.5,20.0,0.28,513.0,486.0,999.0,0.65,20.3,16.5
49,Wisconsin,0.03,642.0,649.0,1291.0,1.00,19.7,20.4,20.6,20.9,20.0,0.03,641.0,653.0,1294.0,1.00,20.5,8.9
50,Wyoming,0.03,626.0,604.0,1230.0,1.00,19.4,19.8,20.8,20.6,20.2,0.03,633.0,625.0,1257.0,1.00,20.0,11.2

Now that data cleaning is done and over with I will save the dataframe and move into EDA

In [61]:
data.to_csv('./data/final_data.csv',index=False)